### ISSUE TITLE
MPM install not working

### ISSUE THREAD

**Issue by Cobwebster** [Cryptkeeper/Minetrack#82] opened 2017-06-22 16:52 UTC
We're unable to compile sqlite3 on our VPS, this is what happens

https://gyazo.com/ae0c78ad0cb077d0aa9b3fe10c537c68

Anyone else having this issue or know how to resolve?

**Comment by hugmanrique** [comment] 2017-06-22 17:25
This issue also happened in another project (https://github.com/mapbox/node-sqlite3/issues/612).

The problem is that nodejs is not available in the path /usr/bin/node. Once you link it with `sudo ln -s "$(which nodejs)" /usr/bin/node`, sqlite3 should install fine.

**Comment by Cobwebster** [comment] 2017-06-22 19:34
Yeah still doesn't seem to work for us.


________________________________

**Comment by hugmanrique** [comment] 2017-06-22 19:57
Can you check all the answers in that issue and check if one of them works for you?

**Comment by Cobwebster** [comment] 2017-06-22 19:59
We've read it all over, none of those solutions work for us sadly. It gives the exact same errors

**Comment by Ryan-Harvey** [comment] 2017-06-22 20:03
`4322 info lifecycle sqlite3@3.1.1~install: sqlite3@3.1.1
4323 verbose lifecycle sqlite3@3.1.1~install: unsafe-perm in lifecycle false
4324 verbose lifecycle sqlite3@3.1.1~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/MineTrack/node_modules/sqlite3/node_modules/.bin:/root/MineTrack/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
4325 verbose lifecycle sqlite3@3.1.1~install: CWD: /root/MineTrack/node_modules/sqlite3
4326 silly lifecycle sqlite3@3.1.1~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
4327 silly lifecycle sqlite3@3.1.1~install: Returned: code: 1  signal: null
4328 info lifecycle sqlite3@3.1.1~install: Failed to exec install script
4329 verbose unlock done using /root/.npm/_locks/staging-5fa55befa36740b2.lock for /root/MineTrack/node_modules/.staging
4330 verbose stack Error: sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
4330 verbose stack Exit status 1
4330 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
4330 verbose stack     at emitTwo (events.js:106:13)
4330 verbose stack     at EventEmitter.emit (events.js:191:7)
4330 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
4330 verbose stack     at emitTwo (events.js:106:13)
4330 verbose stack     at ChildProcess.emit (events.js:191:7)
4330 verbose stack     at maybeClose (internal/child_process.js:891:16)
4330 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
4331 verbose pkgid sqlite3@3.1.1
4332 verbose cwd /root/MineTrack
4333 verbose Linux 3.10.0-514.21.1.el7.x86_64
4334 verbose argv "/usr/bin/node" "/bin/npm" "install" "--build-from-source"
4335 verbose node v6.11.0
4336 verbose npm  v5.0.3
4337 error code ELIFECYCLE
4338 error errno 1
4339 error sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
4339 error Exit status 1
4340 error Failed at the sqlite3@3.1.1 install script.
4340 error This is probably not a problem with npm. There is likely additional logging output above.
4341 verbose exit [ 1, true ]
`

**Comment by Ryan-Harvey** [comment] 2017-06-22 20:04
> 4322 info lifecycle sqlite3@3.1.1~install: sqlite3@3.1.1
4323 verbose lifecycle sqlite3@3.1.1~install: unsafe-perm in lifecycle false
4324 verbose lifecycle sqlite3@3.1.1~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/MineTrack/node_modules/sqlite3/node_modules/.bin:/root/MineTrack/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
4325 verbose lifecycle sqlite3@3.1.1~install: CWD: /root/MineTrack/node_modules/sqlite3
4326 silly lifecycle sqlite3@3.1.1~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
4327 silly lifecycle sqlite3@3.1.1~install: Returned: code: 1  signal: null
4328 info lifecycle sqlite3@3.1.1~install: Failed to exec install script
4329 verbose unlock done using /root/.npm/_locks/staging-5fa55befa36740b2.lock for /root/MineTrack/node_modules/.staging
4330 verbose stack Error: sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
4330 verbose stack Exit status 1
4330 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
4330 verbose stack     at emitTwo (events.js:106:13)
4330 verbose stack     at EventEmitter.emit (events.js:191:7)
4330 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
4330 verbose stack     at emitTwo (events.js:106:13)
4330 verbose stack     at ChildProcess.emit (events.js:191:7)
4330 verbose stack     at maybeClose (internal/child_process.js:891:16)
4330 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
4331 verbose pkgid sqlite3@3.1.1
4332 verbose cwd /root/MineTrack
4333 verbose Linux 3.10.0-514.21.1.el7.x86_64
4334 verbose argv "/usr/bin/node" "/bin/npm" "install" "--build-from-source"
4335 verbose node v6.11.0
4336 verbose npm  v5.0.3
4337 error code ELIFECYCLE
4338 error errno 1
4339 error sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
4339 error Exit status 1
4340 error Failed at the sqlite3@3.1.1 install script.
4340 error This is probably not a problem with npm. There is likely additional logging output above.
4341 verbose exit [ 1, true ]

**Comment by Cobwebster** [comment] 2017-06-22 20:05
logfile,

https://hastebin.com/fipaqalufu.sql

**Comment by Cobwebster** [comment] 2017-06-24 11:15
Any thoughts @hugmanrique ?

**Comment by Cobwebster** [comment] 2017-06-24 12:16
Resolved :)

**Comment by hugmanrique** [comment] 2017-06-24 15:23
How did you finally fix it? It might be useful for others in the future :)

**Comment by Cobwebster** [comment] 2017-06-24 15:42
Basically Ubuntu by default puts a different name on a node or something so we had to change the name of it so it would work. I didn't set it up but I was told that was basically the fix.

**Comment by Classic36MC** [comment] 2017-06-24 16:24
Glad to see you fixed it :)

**Comment by Cobwebster** [comment] 2017-06-25 01:32
@hugmanrique @Classic36MC Where is the number where the graph is based off store? Its given us 2000 and its too high so the graph doesn't really provide great usage for small player loss.

http://www.battleclans.net/

https://gyazo.com/0fbb55d58565928827d3efe5ab49a133

**Comment by hugmanrique** [comment] 2017-06-25 04:31
Currently a setting for this doesn't exist, but you can change this line https://github.com/Cryptkeeper/Minetrack/blob/0955e8dbcd77b2523de0e41c5a5219fcb26046a1/assets/js/graph.js#L47 to any value. Please, create a new issue and close this one for new questions/issues.

**Comment by astei** [comment] 2017-07-02 10:59
I also had this issue too, but I solved it by upgrading the `sqlite3` dependency instead.

**Comment by Chewsterchew** [comment] 2017-07-24 23:36
I cannot for the life of me get this to work. I tried updating node, directly installing `sqlite3`, even looked up some stuff and still cannot get it.

**Comment by Ryan-Harvey** [comment] 2017-07-24 23:38
@Chewsterchew Did you try using the install script within /scripts on a blank canvas?

**Comment by Chewsterchew** [comment] 2017-07-25 01:52
I got it, I installed sqlite3 outside of the Minetrack directory and just moved the folder in.

**Comment by Ryan-Harvey** [comment] 2017-07-25 17:36
Yeah it needs to store data to make a graph out of, without that installed you won't be able to use it.

**Comment by TNTUP** [comment] 2017-07-28 11:06
Setup a new VPS and getting the Sqlite3.1.1 error on debian Jessie... Any solution for this?

**Comment by minecrafter** [comment] 2017-07-28 11:06
I was able to resolve this by manually updating the `sqlite3` dependency in the `package.json`.

**Closed** 2017-08-09 05:55 UTC
