### ISSUE TITLE
No longer able to ping majority of servers

### ISSUE THREAD

**Issue by TehNeon** [Cryptkeeper/Minetrack#168] opened 2020-05-13 20:09 UTC
While attempting to upgrade from Minetrack 5.3.1 to the latest version (5.4.1) I encountered an issue where majority of my servers no longer ping. I created a new instance of Minetrack and in config.json enabled logToDatabase and copied my servers.json file over from my other Minetrack instance.

When actually accessing the Minetrack I'm greeted with a fairly broken appearing instance which can be seen in this screenshot: https://i.imgur.com/N4mfCfq.jpg

Upon shutting it down and enabling "skipUnfurlSrv" and boot it back up I end up with a functional version as seen in this screenshot: https://i.imgur.com/WBOwmLT.jpg

After it boots up with that I can change "skipUnfurlSrv" back off and it'll load up fine again, but in both cases majority of the servers resulting in a Socket timeout.

While attempting to utilize an SRV (play.invadedlands.net) which points to a CNAME (def.skeppylovesflipflops.xyz) appears to fail when pinging, but utilizing the CNAME (def.skeppylovesflipflops.xyz) seems to allow it to ping properly.

**Comment by Cryptkeeper** [comment] 2020-05-13 21:19
I'm seeing this same behavior but assumed it was my own rather strange DNS configuration to blame. What DNS provider are you using?

I'm assuming the issue is at the Node level since it is purely the call to https://nodejs.org/api/dns.html#dns_dns_resolvesrv_hostname_callback that is taking up all the ping timeout. 

If you need SRV support in the short term, there is also the "unfurlSrvCacheTtl" that allows Minetrack to cache an SRV record for a certain amount of time instead of resolving each ping: https://github.com/Cryptkeeper/Minetrack/blob/master/config.json#L14

**Comment by Cryptkeeper** [comment] 2020-05-13 21:25
Also, does this still happen if you revert back to the previous version?

**Comment by Cryptkeeper** [comment] 2020-05-13 21:42
I have released 5.4.2 which fixes at least a typo that is causing some of the issues. I'm still personally still seeing abnormally long resolve times. I'm digging into options for setting a resolve timeout to the #resolveSrv call.

https://github.com/Cryptkeeper/Minetrack/releases/tag/v5.4.2

**Comment by TehNeon** [comment] 2020-05-13 22:19
For testing purposes I've provided a servers.json which has 5 servers in it, which 2 are using alternative ips that properly resolve.

`[
  {
    "name": "InvadedLands (Not Working)",
    "ip": "invadedlands.net",
    "type": "PC"
  },
  {
    "name": "InvadedLands (Working)",
    "ip": "def.skeppylovesflipflops.xyz",
    "type": "PC"
  },
  {
    "name": "PvPLands (Not Working)",
    "ip": "pvplands.net",
    "type": "PC"
  },
  {
    "name": "Arcane (Not Working)",
    "ip": "arcane.cc",
    "type": "PC"
  },
  {
    "name": "MMC (Not Working)",
    "ip": "minemen.club",
    "type": "PC"
  },
  {
    "name": "MMC (Working)",
    "ip": "na.minemen.club",
    "type": "PC"
  },
  {
    "name": "Tapple (Not Working)",
    "ip": "tapple.world",
    "type": "PC"
  }
]`

**Comment by TehNeon** [comment] 2020-05-13 22:23
I went ahead and updated to 5.4.2. 

When the option "skipUnfurlSrv" is enabled, the servers marked as "not working" will timeout. When disabled, they will resolve and ping properly as should be expected.

**Comment by Cryptkeeper** [comment] 2020-05-13 22:38
Great to hear. I'm working on some DNS tweaks to add further logging and improve it's reliability to prevent anything funky happening in the future. 

Thanks for your help!

I'm going to close this issue, please open another if anything starts happening again.

**Closed by Cryptkeeper** 2020-05-13 22:38 UTC
Labels: bug, help wanted
