### ISSUE TITLE
minetrack.me background is white in Firefox

### ISSUE THREAD

**Issue by leeoniya** [Cryptkeeper/Minetrack#192] opened 2020-06-24 17:51 UTC
@Cryptkeeper FYI

**Comment by Cryptkeeper** [comment] 2020-06-24 19:08
Can you share your Firefox version? I use 77.0.1 and I'm not seeing it.

**Comment by leeoniya** [comment] 2020-06-24 19:14
![minetrack](https://user-images.githubusercontent.com/43234/85617487-f133c080-b624-11ea-9786-aa29369a5053.png)

**Comment by Cryptkeeper** [comment] 2020-06-24 19:15
Seems like several of the CSS rules are broken in that screenshot. Is there anything in dev console?

**Comment by leeoniya** [comment] 2020-06-24 19:18
for some reason css errors were disabled in the console. (are they disabled by default? 😕 )

![image](https://user-images.githubusercontent.com/43234/85617850-88991380-b625-11ea-9631-0d28144e338d.png)

**Comment by Cryptkeeper** [comment] 2020-06-24 19:44
Hmm, I'm seeing the same output but none of the display errors. I'll keep trying to reproduce and see what I can get.

**Comment by Cryptkeeper** [comment] 2020-06-25 18:51
Okay, I can't reproduce lol

I'm not sure if this is somehow an issue between macOS/Windows Firefox, but I'll keep digging.

**Comment by Cryptkeeper** [comment] 2020-07-06 18:32
Tracked it down to https://github.com/Cryptkeeper/Minetrack/issues/195.

Closing this issue in favor of that one. Thank you!

**Closed by Cryptkeeper** 2020-07-06 18:32 UTC
Labels: bug, help wanted
