### ISSUE TITLE
Startup takes forever after one day

### ISSUE THREAD

**Issue by Slind14** [Cryptkeeper/Minetrack#83] opened 2017-06-26 17:09 UTC
Hi there,
after one day the startup takes forever for loading the sqlite file. Are there any plans to add mongo or mysql support?

**Comment by astei** [comment] 2017-07-02 10:55
I noticed Minetrack's slow start-up time as well, but only after a few hours.

Adding MongoDB or MySQL support would not solve the issue, however. Minetrack loads the full chart into memory, and the only thing adding MongoDB or MySQL support would do is extend the start-up time and introduce the potential for network latency.

As a stop-gap, I would recommend the following:

* Reduce the ping interval (`pingAll` under `rates` in `config.json`) from the default of every three seconds to five seconds.
* Reduce the amount of data loaded on startup from `86400000` milliseconds (or one day) to three hours (`10800000`ms) by changing your `graphDuration` in your `config.json`.
* Periodically [vacuum the SQLite database](https://sqlite.org/lang_vacuum.html) manually.

Hope this helps.

**Comment by Slind14** [comment] 2017-07-02 16:48
I implemented MongoDB myself and the startup time is within milliseconds,
even after weeks of data. Wit SQLite I killed after 20 minutes and it only
had about one day of data.

**Comment by hugmanrique** [comment] 2017-07-02 18:40
The problem here doesn't lays in what database engine you're using, it is caused by the way Minetrack stores data and doesn't delete it after x time. I would suggest creating an automated Shell script that could be added to the `scripts` directory which would vacuum the SQLite database as @astei suggested.

**Comment by Slind14** [comment] 2017-07-02 20:24
Not really:
https://github.com/Cryptkeeper/Minetrack/blob/master/lib/database.js#L36
Duration isn't more than a day from what I can see.

**Comment by astei** [comment] 2017-07-03 00:27
Actually... I found out why Minetrack start time was so long, and I will be PRing a fix soon.

The basic explanation is "bad database indexes".

**Comment by TNTUP** [comment] 2017-08-05 01:46
53mb file and startup takes a lot of minutes, still no fixes I guess?

**Comment by Cryptkeeper** [comment] 2017-08-09 05:52
Indexes don't make sense as a cause of slowing down query times since they're perfect matches for the queries.

@TNTUP make sure to update from latest master and report back, I believe our culprit was an overly large sort on boot: https://github.com/Cryptkeeper/Minetrack/commit/b2c72c0bfb8b37bdae65c7a5bf8a8c91f6908d5c

**Comment by TNTUP** [comment] 2017-08-09 06:05
Updated and it works :)

02:04:31 9/8/17 - info: Parsed 86318 ping records in 80ms
02:04:31 9/8/17 - info: Queried and parsed ping history in 554ms

**Comment by Cryptkeeper** [comment] 2017-08-09 06:07
Awesome, going to close the issue then 😄

**Comment by TNTUP** [comment] 2017-08-09 06:08
Thanks again for this quick fix!

**Closed by Cryptkeeper** 2017-08-09 06:07 UTC
